import { Providers, ThemeButton } from '@/components'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className="bg-bgColor">
        <Providers>
          <div className="mx-auto w-full max-w-[500px]">{children}</div>
          <ThemeButton />
        </Providers>
      </body>
    </html>
  )
}
